from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


@dataclass(frozen=True)
class DetectionResult:
    profile_id: str
    confidence: float
    evidence: tuple[str, ...]


@dataclass(frozen=True)
class NormalizedResult:
    status: str
    kind: str
    summary: str
    evidence_refs: tuple[str, ...]
    finding_refs: tuple[str, ...] = ()


class ProjectDetector(Protocol):
    def detect(self, workspace: Path) -> DetectionResult: ...


class TechnologyProfile(Protocol):
    def capabilities(self) -> tuple[str, ...]: ...
    def default_validators(self) -> tuple[str, ...]: ...
    def default_commands(self) -> dict[str, tuple[str, ...]]: ...
    def default_policies(self) -> dict[str, Any]: ...


class Validator(Protocol):
    def detect(self, context: dict[str, Any]) -> bool: ...
    def execute(self, context: dict[str, Any]) -> Any: ...
    def parse(self, raw_result: Any) -> Any: ...
    def normalize(self, parsed_result: Any) -> NormalizedResult: ...


class AgentProvider(Protocol):
    def capabilities(self) -> tuple[str, ...]: ...
    def start(self, request: dict[str, Any]) -> str: ...
    def resume(self, session: str) -> None: ...
    def cancel(self, session: str) -> None: ...
    def collect_events(self, session: str) -> list[dict[str, Any]]: ...
    def collect_usage(self, session: str) -> dict[str, Any]: ...


class Reporter(Protocol):
    def render(self, execution: dict[str, Any], format: str) -> bytes: ...
