#!/usr/bin/env python3
"""Generate docs/reference/cli.md from the installed ``harness`` command tree.

The reference is derived from the Typer/Click objects (names, help texts, options, defaults),
so it cannot drift from the code. CI runs ``--check`` and fails when the committed file is stale.

Usage::

    python scripts/gen_cli_docs.py            # rewrite docs/reference/cli.md
    python scripts/gen_cli_docs.py --check    # exit 1 if the file is out of date
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import typer

from governed_harness import __version__
from governed_harness.cli.main import app

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "reference" / "cli.md"


# Typer >= 0.2x vendors its own Click; duck typing keeps this script working with either.
Command = Any


def context(command: Command) -> Any:
    return command.context_class(command)


def walk(command: Command, path: tuple[str, ...]) -> Iterator[tuple[tuple[str, ...], Command]]:
    if hasattr(command, "list_commands"):
        for name in command.list_commands(context(command)):
            sub = command.get_command(context(command), name)
            if sub is not None and not sub.hidden:
                yield from walk(sub, (*path, name))
    else:
        yield path, command


def describe_default(param: Any) -> str:
    default = param.default
    if default is None or param.required or callable(default):
        return ""
    if isinstance(default, Path) and default == Path.cwd():
        return "current working directory"
    if getattr(param, "is_flag", False) and param.secondary_opts:
        return param.opts[0] if default else param.secondary_opts[0]
    if isinstance(default, bool):
        return "true" if default else "false"
    return f"`{default}`"


def param_type(param: Any) -> str:
    if getattr(param, "is_flag", False):
        return "flag"
    kind = param.type
    if hasattr(kind, "choices"):
        return " \\| ".join(f"`{c}`" for c in kind.choices)
    return kind.name.lower()


def render() -> str:
    root = typer.main.get_command(app)
    commands = list(walk(root, ()))
    lines = [
        "# CLI reference",
        "",
        "<!-- Generated by scripts/gen_cli_docs.py from the installed command tree. Do not edit by hand. -->",
        "",
        f"`harness` {__version__} exposes {len(commands)} commands. Every command accepts `--help`.",
        "Exit codes are documented in [exit codes](exit-codes.md).",
        "",
        "| Command | Summary |",
        "|---|---|",
    ]
    for path, command in commands:
        name = " ".join(path)
        summary = (command.get_short_help_str(limit=120) or "—").replace("|", "\\|")
        anchor = "harness-" + "-".join(path)
        lines.append(f"| [`harness {name}`](#{anchor}) | {summary} |")
    for path, command in commands:
        name = " ".join(path)
        lines += ["", f"## harness {name}", ""]
        if command.help:
            lines += [command.help.strip(), ""]
        usage = " ".join(command.collect_usage_pieces(context(command)))
        lines += ["```text", f"harness {name} {usage}".rstrip(), "```", ""]
        params = [p for p in command.params if p.name != "help"]
        if not params:
            continue
        lines += ["| Option | Type | Required | Default | Description |", "|---|---|---|---|---|"]
        for param in params:
            if param.param_type_name == "option":
                flags = ", ".join(f"`{opt}`" for opt in [*param.opts, *param.secondary_opts])
                help_text = (param.help or "").replace("|", "\\|")
            else:
                flags = f"`{param.human_readable_name}`"
                help_text = ""
            required = "yes" if param.required else "no"
            lines.append(
                f"| {flags} | {param_type(param)} | {required} | {describe_default(param)} | {help_text} |"
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed reference is stale"
    )
    args = parser.parse_args(argv)
    content = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run: python scripts/gen_cli_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
