#!/usr/bin/env python3
"""Generate docs/reference/task-file.md from schemas/v1/task.schema.json.

The JSON Schema is itself generated from the typed domain model by scripts/generate_schemas.py,
so this reference follows the contract. ``--check`` fails when the committed file is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schemas" / "v1" / "task.schema.json"
TARGET = ROOT / "docs" / "reference" / "task-file.md"


def type_of(spec: dict[str, Any]) -> str:
    if "$ref" in spec:
        name = spec["$ref"].rsplit("/", 1)[-1]
        return f"[{name}](#{name.lower()})"
    if "anyOf" in spec:
        return " or ".join(type_of(option) for option in spec["anyOf"])
    if "enum" in spec:
        return " \\| ".join(f"`{value}`" for value in spec["enum"])
    if "const" in spec:
        return f"`{spec['const']}`"
    kind = spec.get("type", "any")
    if kind == "array":
        return f"array of {type_of(spec.get('items', {}))}"
    if (
        kind == "object"
        and "additionalProperties" in spec
        and isinstance(spec["additionalProperties"], dict)
    ):
        return f"map of {type_of(spec['additionalProperties'])}"
    if spec.get("format"):
        return f"{kind} ({spec['format']})"
    return str(kind)


def constraints(spec: dict[str, Any]) -> str:
    parts = []
    for key, label in (
        ("minLength", "min length"),
        ("maxLength", "max length"),
        ("pattern", "pattern"),
    ):
        if key in spec:
            parts.append(f"{label} `{spec[key]}`" if key == "pattern" else f"{label} {spec[key]}")
    for option in spec.get("anyOf", []):
        if "maxLength" in option:
            parts.append(f"max length {option['maxLength']}")
    if "default" in spec and spec["default"] not in (None, [], {}):
        parts.append(f"default `{json.dumps(spec['default'])}`")
    return "; ".join(parts)


def table(schema: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    rows = ["| Field | Type | Required | Constraints |", "|---|---|---|---|"]
    for name, spec in schema.get("properties", {}).items():
        rows.append(
            f"| `{name}` | {type_of(spec)} | {'yes' if name in required else 'no'} | {constraints(spec)} |"
        )
    return rows


def render() -> str:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    lines = [
        "# Task file reference",
        "",
        "<!-- Generated by scripts/gen_schema_docs.py from schemas/v1/task.schema.json. Do not edit by hand. -->",
        "",
        f"Contract: `{schema.get('$id', 'task.schema.json')}` (JSON Schema 2020-12).",
        "",
        "`harness task create --file task.yaml` accepts YAML or JSON and persists a task that",
        "validates against this schema. The loader is lenient: a requirement or acceptance",
        "criterion may be a plain string, a missing `taskId` or item id is generated, snake_case",
        "aliases are accepted, `projectId` defaults to the project and `schemaVersion` and",
        "`createdAt` are set by the harness. Unknown top-level keys are ignored, and a missing",
        "`title` or `intent` is currently stored as the text `None` instead of being rejected",
        "(issue #29), so always provide both.",
        "",
        "## Task",
        "",
        *table(schema),
    ]
    for name, definition in sorted(schema.get("$defs", {}).items()):
        lines += ["", f"## {name}", "", *table(definition)]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    content = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run: python scripts/gen_schema_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date")
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
