const $ = (id) => document.getElementById(id);
const output = $('output');
function headers(json=false){const h={};const token=$('token').value.trim();if(token)h.Authorization=`Bearer ${token}`;if(json)h['Content-Type']='application/json';return h}
function base(){return $('baseUrl').value.replace(/\/$/,'')}
async function request(paths,options={}){let last;for(const path of paths){try{const r=await fetch(base()+path,{...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body={raw:text}}if(r.ok)return body;last=new Error(`${r.status} ${r.statusText}: ${text}`)}catch(e){last=e}}throw last||new Error('No route succeeded')}
function show(data){output.textContent=JSON.stringify(data,null,2)}
function summary(data){const exec=data.execution||data;const fields={ID:exec.execution_id||exec.id,Status:exec.status,Phase:exec.current_phase||exec.phase,Task:exec.task_id,ChangeSet:exec.change_set_digest||exec.changeset_digest,Updated:exec.updated_at};const dl=$('executionSummary');dl.innerHTML='';for(const [k,v] of Object.entries(fields)){if(v===undefined||v===null)continue;const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=String(v);dl.append(dt,dd)}$('executionStatus').textContent=exec.status||'UNKNOWN';const digest=exec.change_set_digest||exec.changeset_digest||(data.change_set||{}).digest;if(digest)$('digest').value=digest}
$('connect').onclick=async()=>{try{const data=await request(['/health','/api/health','/v1/health']);$('health').textContent=data.status||'Connected';$('health').className='status pass';show(data)}catch(e){$('health').textContent='Connection failed';$('health').className='status fail';show({error:String(e)})}}
$('loadExecution').onclick=async()=>{const id=$('executionId').value.trim();if(!id)return show({error:'Execution ID is required'});try{const data=await request([`/executions/${encodeURIComponent(id)}`,`/api/executions/${encodeURIComponent(id)}`,`/v1/executions/${encodeURIComponent(id)}`]);summary(data);show(data)}catch(e){show({error:String(e)})}}
$('loadTrace').onclick=async()=>{const id=$('executionId').value.trim();if(!id)return show({error:'Execution ID is required'});try{show(await request([`/executions/${encodeURIComponent(id)}/trace`,`/api/executions/${encodeURIComponent(id)}/trace`,`/v1/executions/${encodeURIComponent(id)}/trace`]))}catch(e){show({error:String(e)})}}
$('submitDecision').onclick=async()=>{const id=$('executionId').value.trim();const payload={decision:$('decision').value,rationale:$('rationale').value.trim(),change_set_digest:$('digest').value.trim(),actor:'human:web'};if(!id||!payload.rationale||!payload.change_set_digest)return show({error:'Execution ID, rationale, and exact ChangeSet digest are required'});if(!confirm(`Submit ${payload.decision} for digest ${payload.change_set_digest}?`))return;try{const data=await request([`/executions/${encodeURIComponent(id)}/decisions`,`/api/executions/${encodeURIComponent(id)}/decisions`,`/v1/executions/${encodeURIComponent(id)}/decisions`],{method:'POST',body:JSON.stringify(payload)});summary(data);show(data)}catch(e){show({error:String(e)})}}
$('copy').onclick=()=>navigator.clipboard?.writeText(output.textContent);
